export const PRODUCTS = [
    {
        id: 1,
        category: 1,
        name: 'TECLADO LOGITECH',
        description: 'ERGONIMICO',
        weight: '750GR',
        price: 200
    },
    {
        id: 2,
        category: 1,
        name: 'TECLADO MICROSOFT',
        description: 'COLOR NEGRO',
        weight: '250GR',
        price: 100,
    },
    {
        id: 3,
        category: 2,
        name: 'MONITOR SAMSUNG',
        description: 'LED 23 PULGADAS',
        weight: '850GR',
        price: 300,
    },
    {
        id: 4,
        category: 2,
        name: 'MONITOR LG',
        description: 'LED 23 PULGADAS, IPS',
        weight: '750 GR',
        price: 250,
    },
    {
        id: 5,
        category: 3,
        name: 'MOUSE LOGITECH',
        description: 'ERGONOMICO',
        weight: '150GR',
        price: 75,
    },
    {
        id: 6,
        category: 3,
        name: 'MOUSE MICROSOFT',
        description: 'COLOR NEGRO',
        weight: '100GR',
        price: 50,
    },
    {
        id: 7,
        category: 4,
        name: 'MICROFONO USB',
        description: 'COLOR NEGRO',
        weight: '250GR',
        price: 200,
    },
    {
        id: 8,
        category: 4,
        name: 'MICROFONO ELGATO',
        description: 'INCLUYE FILTRO DE RUIDO',
        weight: '500GR',
        price: 300,
    },
]